openapi: 3.1.1
info:
  title: Hoseki API
  version: "1.0.0"
  description: Documentación de la API para los distintos módulos de la joyeria Hoseki.

paths: {}

components: {}

# Referencias a archivos externos
