# Configuracion para perfiles
spring:
  application:
    name: springboot-sa-ha1
  profiles:
    active: prod
jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS}
#
#logging:
#  level:
#    org.springframework.web: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql: TRACE


